# Introduction to Stochastic Processes {#intro}
 
The course will cover the probabilistic framework for stochastic models
of real-world applications with emphasis on actuarial work. We will
illustrate some practical actuarial problems for which we will develop
mathematical models, tools and techniques for analysing and quantifying
the uncertainty of the problems.

Here are some of the examples which will be covered later in the course.

Examples of real world processes
================================

::: {.example}
**Example 1**. *(**No claims discount systems (NCD)**) A well-known
model widely used by auto insurance companies is the **no claims
discount system**, in which an insured receives a discount for a claim
free year, while the insured is penalised by an additional premium when
one or more accidents occur.*

*An example of the NCD system in UK may be structured as follows:*

    *Level*     *7*      *6*     *5*     *4*     *3*     *2*     *1*
  ----------- -------- ------- ------- ------- ------- ------- -------
   *Premium*   *100%*   *75%*   *65%*   *55%*   *45%*   *40%*   *33%*

*The rules for moving between these levels are as follows:*

-   *For a claim-free year, a policyholder moves down 1 level.*

-   *Levels 4$-$7:*

    -   *For every one claim, the policyholder moves up 1 level or
        remains at level 7.*

    -   *For every two or more claims, move to, or remains at, level 7.*

-   *Levels 2$-$3:*

    -   *For every one claim, move up 2 levels.*

    -   *For every two claims, move up 4 levels.*

    -   *For every three or more claims, move to level 7.*

-   *Level 1:*

    -   *For every one claim, move to level 4.*

    -   *For every two claims, move to level 6.*

    -   *For every three or more claims, move to level 7.*

*The no claims discount system is a form of experience rating consisting
of a finite number of levels (or classes), each with its own premium.
The 7 levels are experience-rated as described above.*

*For the NCD model, questions of interest may include:*

1.  *For 10,000 policyholders at level 7, estimate the *expected
    numbers* at each discount level at a given time, or once stability
    has been achieved.*

2.  *What is the *probability* that a policyholder who is at a specific
    discount level (i.e. one of the levels 1-6) has no discount after 2
    years?*

3.  *What is the *distribution* of being in one of the levels at time 5
    years?*

4.  *Suppose a large number of people having the same claim
    probabilities take out policies at the same time. What is the
    proportion would you expect to be in each discount level in the long
    run?*

*What would be a suitable model to study the NCD system? As opposed to a
**deterministic model** for which its outcomes are fixed, the outcomes
of the NCD model are uncertain. It turns out that the NCD system can be
studied within the framework of Markov chains, which are examples of
stochastic processes. The use of matrix algebra provides a powerful tool
to understand and analyse the processes.*

*The evolution of the states or levels can be described the random
variables $X_0, X_1,X_2, \ldots$ and probability distributions, where
$X_n$ is the level of the policyholder at time $n$. In this example, the
set of all states called the state space is discrete, which consists of
seven levels, and the time variable is also discrete. This is an example
of a **discrete time, discrete state space stochastic process**.*
:::

::: {.example}
**Example 2**. *(**Poisson processes**) Consider the number of claims
that occur up to time $t$ (denoted by $N_t$) from a portfolio of health
insurance policies (or other types of insurance products). Suppose that
the average rate of occurrence of claims per time unit (e.g. day or week
) is given by $\lambda$.*

*Here are some questions of interest:*

1.  *On average, 20 claims arrive every day, what is the probability
    that more than 100 claims arrive within a week?*

2.  *What is the expected time until the next claim?*

*In this example, the state space consists of all whole numbers
$\{0, 1, 2, \ldots\}$, while the time variable is continuous. The
process is a **continuous-time stochastic process with discrete state
space**. The model used to model the insurance claims is an example of
**Poisson processes**. The Poisson process is one of the most
widely-used counting processes. Even thought we know that claims occur
at a certain rate, but completely at random. Moreover, the timing
between claims seem to be completely random.*

*Later, we will see that there are several ways to describe this
process. One can focus on the number of claims that occur up to time $t$
or the times between those claims when they occur. Many important
properties of Poisson processes will be discussed.*
:::

::: {.example}
**Example 3**. *(**Markov processes**) Suppose that we observe a total
of $n$ independent lives all aged between $x$ and $x + 1$. For life $i$,
we define the following terms:*

-   *$x+ a_i$ is the age at which observation
    begins,$\quad 0 \le a_i < 1$.*

-   *$x+ b_i$ is the age at which observation ends, if life does not
    die, $\quad 0 \le b_i < 1$.*

-   *$x+ t_i$ is the age at which observation stops, by death or
    censoring.*

-   *$d_i = 1$, if life $i$ dies, otherwise $d_i = 0$, if life $i$
    censored.*

*For example, consider the following mortality data on eight lives all
aged between $70$ and $71$.*

   *Life*   *$a_i$*   *$b_i$*   *$d_i$*   *$t_i$*
  -------- --------- --------- --------- ---------
    *1*       *0*       *1*       *1*     *0.25*
    *2*       *0*       *1*       *1*     *0.75*
    *3*       *0*       *1*       *0*       *1*
    *4*      *0.1*     *0.6*      *1*      *0.5*
    *5*      *0.2*     *0.7*      *1*      *0.6*
    *6*      *0.2*     *0.4*      *0*      *0.4*
    *7*      *0.5*      *1*       *1*     *0.75*
    *8*      *0.5*    *0.75*      *0*     *0.75*

*How would one use this dataset to estimate the probability that a life
aged 70 dies before age $70 + t$ or survives to at least age $70 + t$,
for $t \in [0,1)$?*

*In this example, we can represent the process by $\{X_t\}_{t \ge 0}$
with two possible states (alive or dead). This model is also an example
of a **continuous-time stochastic process with discrete state space**.*

*Here, we illustrate three actuarial applications which can be modelled
by some **stochastic processes**. We should also emphasis that the
outcome of one of the above processes is not fixed or uncertain. The
course will provide important tools and techniques to analyse the
problems with the goal of quantifying the uncertainty in the system.*
:::

Review of probability theory
============================

Random variables
----------------

The dynamics of a stochastic process are describes by random variables
and probability distributions. This section provides a brief discussion
of the properties of random variables.

The probability theory is about random variables. Roughly speaking, a
random variable can be regarded as an uncertain, numerical quantity
(i.e. the value in $\mathbb{R}$) whose possible values depend on the
outcomes of a certain random phenomenon. The random variable is usually
denoted by a capital letter $X, Y, \ldots,$ etc..

More precisely, let $S$ be a sample space. A **random variable** $X$ is
a real-valued function defined on the sample space $S$,
$$X : S \rightarrow \mathbb{R}.$$ Hence, the random variable $X$ is a
function that maps outcomes to real values.

::: {.example}
**Example 4**. *Two coins are tossed simultaneously and the outcomes are
$HH, HT, TH$ and $TT$. We can associate the outcomes of this experiment
with the set $A = \{1,2,3,4 \}$, where $X(HH) = 1, X(HT) = 2, X(TH) = 3$
and $X(TT) = 4$. Assume each of the outcomes has an equal probability of
1/4. Here, we can associate a function $P$ (known as a probability
measure) defined on $S = \{HH, HT, TH, TT \}$ by
$$P(HH) = 1/4,  P(HT) = 1/4,  P(TH) = 1/4,  P(TT) = 1/4.$$*
:::

A probability measure $P : \mathcal{A} \rightarrow [0,1]$, where
$\mathcal{A}$ is a collection of subsets of $S$, has the following
properties

1.  $0 \le P(A), \quad A \subset S$.

2.  $P(S) = 1$.

3.  If $A_i \cap A_j = \emptyset$ for $i,j = 1,2, \ldots$, and
    $i \neq j$ where $A_j \subset S$, then
    $$P(\cup^\infty_{i=1} A_i)  = \sum^\infty_{i=1} P(A_i).$$

Random variables can be discrete or continuous. If the range of a random
variable is finite or countably infinite, then the random variable is a
**discrete random variable**. Otherwise, if its range is an uncountable
set, then it is a **continuous random variable**.

Probability distribution
------------------------

The probability distribution of a random variable $X$ is a function
describing all possible values of $X$ and their corresponding
probabilities or the likelihood of obtaining those values of $X$.
Functions that define the probability measure for a discrete or a
continuous random variable are the **probability mass function (pmf)**
and the **probability density function (pdf)**, respectively.

Suppose $X$ is a discrete random variable. Then the function
$$f(x) = P(X = x)$$ that is defined for each $x$ in the range of $X$ is
called the **probability mass function** (p.m.f) of a random variable
$X$.

Suppose $X$ is a continuous random variable with c.d.f $F$ and there
exists a nonnegative, integrable function $f$,
$f: \mathbb{R} \rightarrow [0, \infty)$ such that
$$F(x) = \int_{-\infty}^x f(y)\, dy$$ Then the function $f$ is called
the **probability density function** (p.d.f) of a random variable $X$.

Examples of discrete and continuous random variables {#examples-of-discrete-and-continuous-random-variables .unnumbered}
----------------------------------------------------

The main quantities of interest in a portfolio of motor insurance are
the number of claims arriving in a fixed time period and the sizes of
those claims. Clearly, the number of claims can be describe by a
discrete random variable, whose range is finite or countably infinite.
On the other hand, the claim sizes can be describe by a continuous
random variable defined over continuous sample spaces.

::: {.example}
**Example 5**. *Let $N$ denote the number of claims which arise up to a
given time. The range of all possible values $N$ is
$\mathbf{N} \cup \{0\}$. Here $N$ is an example of discrete random
variable. We could model the number of claims by the Poisson family of
distributions. Recall that a random variable $N$ has a Poisson
distribution with the parameter $\lambda$ if its probability
distribution is given by
$$f(n) = e^{- \lambda} \frac{\lambda^n}{n !}, \quad \text{ for } n = 0,1,\ldots.$$*

*Now suppose further that the number of claims $N$ which arise on a
portfolio in a week has a $\text{Poisson}(\lambda)$ where $\lambda = 5$.
Calculate the following quantities:*

1.  *$\Pr(N \ge 6)$.*

2.  *$\mathrm{E}[N]$.*
:::

1.  $\Pr(N \ge 6) = 1 - \Pr(N \le 5) = 1 - \sum_{n=0}^5 f(n) = 0.3840393.$

2.  Clearly, $\mathrm{E}[N] = \lambda = 5$.

::: {.example}
**Example 6**. *Let $X$ denote the claim sizes in a given time period.
The range of all possible values $X$ is the set of all non-negative
numbers. Here $X$ is an example of a continuous random variable.
Suitable families of distributions which could be used to modelled claim
sizes are \"fat tails\" distribution. They allow for possibilities of
large claim sizes.*

*Examples of fat-tailed distributions include*

-   *the Pareto distribution,*

-   *the Log-normal distribution,*

-   *the Weibull distribution with shape parameter greater than 0 but
    less than 1, and*

-   *the Burr distribution.*
:::

The course \"SCMA 470 Risk Analysis and Credibility\" provides more
details about the loss distribution.

Conditional probability
-----------------------

A stochastic process can be defined as a collection or sequence of
random variables. The concept of **conditional probability** plays an
important role to analyse dependency between random variables in the
process. Roughly speaking, conditional probability is the probability of
seeing some event knowing that some other event has actually occurred.

Let $A$ and $B$ be two events (elements of $\mathcal{A}$). The
conditional probability of event $A$ given $B$ denoted by $P(A | B)$ is
defined as $$P(A|B) =  \frac{P(A \cap B)}{P(B)}.$$ Note that
$P(A \cap B)$ is often called the joint probability of $A$ and $B$, and
$P(A)$ and $P(B)$ are often called the marginal probabilities of $A$ and
$B$, respectively.

The events $A$ and $B$ are independent if the occurrence of either one
of the events does not affect the probability of occurrence of the
other. More precisely, the events $A$ and $B$ are independent if
$$P(A \cap B) = P(A)P(B),$$ or equivalently, $$P(A|B) =  P(A).$$

Law of total probability {#law-of-total-probability .unnumbered}
------------------------

Suppose there are three events: $A$, $B$, and $C$. Events $B$ and $C$
are distinct from each other while event $A$ intersects with both
events. We do not know the probability of event $A$. However, partial
information and dependencies between events can be used to calculate the
probability of event $A$, i.e. we know the probability of event A under
condition B and the probability of event A under condition C.

The total probability rule states that by using the two conditional
probabilities, we can find the probability of event A, which is
$$P(A) = P(A \cap B) + P(A \cap C).$$ In general, suppose
$B_1, B_2, \ldots B_n$ be a collection of events that partition the
sample space. Then for any event $A$,
$$P(A) = \sum_{i = 1}^n   P(A \cap B_i )  = \sum_{i = 1}^n   P(A | B_i ) P(B_i) .$$

::: {.example}
**Example 7**. *Suppose in a particular study area, the vaccination rate
for the yearly flu virus is 70%. Suppose of those vaccinated, 10% of the
residents still get the flu that year. Calculate the conditional
probability of someone getting the flu in this area given that the
person was vaccinated.*
:::

::: {.example}
**Example 8**. *You are an invester buying shares of a company. You have
discovered that the company is planning to introduce a new project that
is likely to affect the company's stock price. You have determined the
following probabilities:*

-   *There is a 80% probability that the new project will be launched.*

-   *If a company launches the project, there is a 85% probability that
    the company's stock price will increase.*

-   *If a company does not launch the project, there is a 30%
    probability that the company's stock price will increase.*
:::

Calculate the probability that the company's stock price will increase.

Conditional distribution and conditional expectation
----------------------------------------------------

Let $X$ and $Y$ be two discrete random variables with joint probability
mass function $$f(x,y) = P(X = x, Y = y).$$ If $X$ and $Y$ are
continuous random variables, the joint probability density function
$f (x, y)$ satisfies
$$P( X \le x, Y \le y) = \int_{-\infty}^x \int_{-\infty}^y f(u,v) \, du\, dv.$$

When no information is given about the value of $Y$, the marginal
probability density function of $X$, $f_X(x)$ is used to calculate the
probabilities of events concerning $X$. However, when the value of $Y$
is known, to find such probabilities, $f_{X|Y} (x|y)$, the conditional
probability density function of $X$ given that $Y = y$ is used and is
defined as follows: $$f_{X|Y} (x|y)  = \frac{f(x,y)}{f_Y(y)}$$ provided
that $f_Y (y) > 0$. The conditional mass function of $X$ is defined in a
similar manner. $$P(X = x | Y = y) = \frac{P(X = x, Y = y)}{P(X = x)}.$$

Note also that the conditional probability density function of $X$ given
that $Y = y$ is itself a probability density function, i.e.
$$\int_{-\infty}^\infty f_{X|Y}(x|y)\, dx  =  1.$$

Note that the conditional probability distribution function of $X$ given
that $Y = y$, the conditional expectation of $X$ given that $Y = y$ can
be as follows:
$$F_{Y|X}(x|y) = P(X \le x | Y = y) = \int_ {-\infty}^x f_{X|Y}(t|y) \, dt$$
and
$$\mathrm{E}(X|Y = y) =  \int_{-\infty}^{\infty} x  f_{X|Y}(x|y) \, dx,$$
where $f_Y(y) > 0$.

Note that if $X$ and $Y$ are independent, then $f_{X|Y}$ coincides with
$f_X$ because
$$f_{X|Y}(x|y) = \frac{f(x,y)}{f_Y(y)} =\frac{f_X(x)f_Y(y)}{f_Y(y)} = f_X(x).$$

Central Limit Theorem
---------------------

This section introduces the Central Limit Theorem, which is an important
theorem in probability theory. It states that the mean of $n$
independent and identically distributed random variables has an
approximate normal distribution given a sufficiently large $n$. This
applies to a collection of random variables from any distribution with a
finite mean and variance. In summary we can use the Central Limit
Theorem to extract probabilistic information about the sums of
independent and identical random variables.

Central Limit Theorem {#central-limit-theorem-1 .unnumbered}
---------------------

Let $X_1, X_2, \ldots$ be a sequence of i.i.d. random variables with a
finite mean $\mathrm{E}[X_i] = \mu$ and finite variance
$\mathrm{Var}[X_i] = \sigma^2$. Let $Z_n$ be the normalised average of
the first $n$ random variables $$\begin{aligned}
        Z_n &= \frac{\sum_{i=1}^n X_i/n  - \mu}{\sigma/\sqrt{n}} \\
               &= \frac{X_1 + X_2 + \ldots + X_n  - n\mu}{\sigma \sqrt{n}}.
    \end{aligned}$$ Then $Z_n$ converges in distribution to a standard
normal distribution.

Stochastic processes
====================

Evolution of a random process is at least partially random, and each run
the process leads to potentially a different outcome. It is of great
interest to understand or model the behaviour of a random process by
describing how different states, represented by random variables $X$'s,
evolve in the system over time. Just as probability theory is considered
as the study of mathematical models of random phenomena, the theory of
stochastic processes plays an important role in the study of
time-dependent random phenomena. Stochastic processes can be used to
represent many different random phenomena from different fields such as
science, engineering, finance, and economics.

A **stochastic process** is a collection of random variables
$\{ X_t : t \in T\}$ defined on a common sample space, where

-   $t$ is a parameter running over some index set $T$, called the
    **time domain**.

-   The common sample space of the random variables (the range of
    possible values for $X_t$) denoted by $S$ is called the **state
    space** of the process.

1.  The set of random variables may be dependent or need not be
    identically distributed.

2.  Techniques used to study stochastic processes depend on whether the
    state space or the index set (the time domain) are discrete or
    continuous.

Classification of stochastic processes
--------------------------------------

Stochastic processes can be classified on the basis of the nature of
their state space and index set.

1.  **Discrete state space with discrete time changes** : No claims
    discount (NCD) policy: A car owner purchases a motor insurance
    policy for which the premium charged depends on the claim record.
    Let $X_t$ denote the discount status of a policyholder with three
    levels of discount, i.e. $S = \{0,1,2\}$ corresponding to three
    discount levels of 0%, 20% and 40% and the time set is
    $T = \{0,1,2,\ldots\}$. Both time and state space are discrete.

2.  **Discrete state space with continuous time changes** : In a health
    insurance system, an insurance company may classify policyholders as
    Healthy, Sick or Dead, i.e. $S = \{H, S, D\}$. The time domain can
    be taken as continuous, $T = [0,\infty)$.

3.  **Continuous state space with continuous time changes** : Let $S_t$
    be the total amount claimed by time $t \in T$ where $T = [0,\infty)$
    and the state space is $\mathbb{R}$. Both time and state space are
    continuous. Some continuous time stochastic process taking value in
    a continuous state space will be studied in Risk Analysis and
    Credibility course.

4.  **Continuous state space with discrete time changes** : The outcomes
    of the above claim process $S_t$ could be recorded continuously,
    however, we may choose to model the values only at discrete time,
    for e.g. the total claim amounts at the end of each day. This may
    due to the limitation of the measurement process (for e.g. expensive
    to measure). Hence, the time domain is discrete but the state space
    is continuous.

In case that claim amounts are recorded to the nearest baht or in
satang, i.e. discrete state space, we could also approximate or model
the process by using a discrete state space, rather than continuous.

Random walk: an introductory example
------------------------------------

One of the simplest examples of a stochastic process is a simple random
walk. Consider a simple model of the price of a stock measured in
satang. For each trading day $n = 0,1,2, \ldots$, the stock price
increases by 1 satang with probability $p$ or decreases by 1 satang with
probability $q = 1-p$. Let $X_n$ denote the stock price at day $n$ and
$X_0 = 100$, i.e. $X_0 =$. This simple model is called a simple random
walk.

In the simple random walk process, time is discrete (as observed at the
end of each day) and the state space is discrete. The stochastic model
has an infinite number of outcomes known as **stochastic realisations or
sample paths**. A **sample path** is then just the sequence of a
particular set of experiments. Graphs of some stochastic realisations of
the simple random walk with $p = 0.5$ and $a = 100$ are shown in Figure
[1](#fig:SamplePaths){reference-type="ref" reference="fig:SamplePaths"}.

![Some stochastic realisations of the simple random
walk](SamplePaths.pdf){#fig:SamplePaths width="4in"}

A complete description of the simple random walk, observed as a
collection of $n$ random variables at time points
$t_1, t_2, \ldots, t_n$ can be specified by the joint distribution of
$X_{t_1}, X_{t_2}, \ldots, X_{t_n}$, i.e.
$$F(x_1, x_2, \ldots, x_n) = \Pr(X_{t_1} \le x_1, X_{t_2} \le x_2, \ldots, X_{t_n} \le x_n).$$
However, the **multidimensional distribution function cannot be easily
written in a closed form** unless the random variables have a
multivariate normal distribution. In practice, it is more convenient to
deal with some stochastic processes via some simple **intermediary
processes** or under some addition assumptions.

In general, a simple random walk $X_n$ is a discrete-time stochastic
process defined by

-   $X_0 = a$ and

-   for $n \ge1$,
    $$X_n = a + \sum_{i=1}^n  Z_i, \text{ where } Z_i = \begin{cases}
        1, & \text{ with probability } p  \\
        -1, & \text{ with probability } q =  1- p.  
     \end{cases}$$

1.  When $p = 1/2$, the value of the process increases or decreases
    randomly by 1 unit with equal probability. In this case, the process
    is known as a **symmetric** random walk.

2.  The (intermediary) process $\{ Z_i : i \in \mathbb{N}\}$ is a
    sequence of independent identically distributed (i.i.d.) random
    variables. The process $X_t$ themselves are neither independent nor
    identically distributed. This process $Z_i$ is also known as **white
    noise process**.

::: {.example}
**Example 9**. *Explain why the simple random process $X_n$ is neither
independent nor identically distributed.*
:::

Suppose that $X_0 = 100$. Firstly, we will show that $X_n$ is not
independent. From definition, the process $X_n$ can be written as
$$X_n = X_{n-1} + Z_n.$$ That is, the value of $X_n$ is the previous
value plus a random change of 1 or $-1$. Therefore, the value of the
process depends on the previous value and they are not independent. For
e.g.,
$$\Pr(X_2 = 102) > 0 \quad \text{ but } \quad  \Pr(X_2 = 102 | X_1 = 99) = 0.$$

The process $X_n$ cannot be identically distributed. For e.g. $X_1$ can
take the values of 99 and 101, while $X_2$ can take three different
values of 98, 100 and 102.

::: {.example}
**Example 10**. *Let $$\begin{aligned}
    \mu &= \mathrm{E}[Z_i] \\
    \sigma^2 &= \mathrm{Var}[Z_i] \end{aligned}$$ Calculate the
expectation ($\mu$) and variance ($\sigma^2$) of the random variable
$Z_i$.*
:::

$$\begin{aligned}
    \mu &= \mathrm{E}[Z_i] = 1\cdot p + (-1) \cdot q = p - q.\\\end{aligned}$$
$$\begin{aligned}
    \sigma^2 &= \mathrm{Var}[Z_i] \\
            &=\mathrm{E}[Z_i^2] - (\mathrm{E}[Z_i] )^2 \\
            &= 1 - (p-q)^2  = (p+q)^2 - (p-q)^2\\
            &= 4pq. \end{aligned}$$

::: {.example}
**Example 11**. *Calculate the expectation and variance of the process
$X_n$ at time $n$.*
:::

$$\begin{aligned}
     \mathrm{E}[X_n] &=  \mathrm{E}[a + \sum_{i=1}^n Z_i] = a + n\mu.\end{aligned}$$
$$\begin{aligned}
    \mathrm{Var}[X_n]&= \mathrm{Var}[a + \sum_{i=1}^n Z_i]  = n \sigma^2.\end{aligned}$$
It should be noted that the variance of $X_n$ increases with time.

::: {.example}
**Example 12**. *For the random process, calculate
$$\Pr(X_2 = 98, X_5 = 99 | X_0 = 100).$$*
:::

The process $X_n$ must decrease on the first two days, which happens
with probability $(1-p)^2$. Independently, it must then increases on
another two days and decrease on one day (not necessarily in that
order), giving three different possibilities. Each of these has
probability $p^2(1-p)$. So
$$\Pr(X_2 = 98, X_5 = 99 | X_0 = 100) = (1-p)^2 \cdot 3 p^2(1-p) = 3p^2(1-p)^3.$$

In what follows, we will see that exact calculations are possible for
the simple random walk process. Note also that it is sufficient to
understand the behaviour of the random walk when it starts at $X_0 = 0$.

::: {.example}
**Example 13**. *For the random process with $X_0 = 0$, $X_{2n}$ is
always even and $X_{2n+1}$ is always odd. Based on the binomial
distribution, show that $$\begin{aligned}
    \Pr(X_{2n} = 2m) &= {2n \choose n+m} p^{n+m} q^{n-m}, \quad   -n \le m \le n \\
    \Pr(X_{2n+1} = 2m+1) &= {2n + 1 \choose n+m+1} p^{n+m+1} q^{n-m}, \quad   -n-1 \le m \le n.\end{aligned}$$*
:::

Let $A$ denote the number of $+1$ and $B$ denote the number of $-1$.
Then $A + B = 2n$ and $X_{2n} = A - B$ (i.e. the position at time $2n$).
Hence, $$\begin{aligned}
    \Pr(X_{2n} = 2m) &= \Pr( A - B = 2m) \\
    &= \Pr( A - (2n - A) = 2m)  =   \Pr( 2A - 2n  = 2m) =   \Pr( A   = m + n)\\
    &= {2n \choose n+m} p^{n+m} q^{2n-(n+m)}, \quad   -n \le m \le n \\
    &= {2n \choose n+m} p^{n+m} q^{n-m}, \quad   -n \le m \le n.\end{aligned}$$

